namespace DFC.App.JobProfile.Data.Enums
{
    public enum ContentRelationship
    {
        hasWitRestriction,
        hasWitOtherRequirement,
        hasWorkingLocation,
        hasHtbDirectRoute,
        hasWorkingEnvironment,
        hasHtbOtherRoute,
        hasDayToDayTask,
        hasHtbApprenticeshipRoute,
        hasONetOccupationalCode,
        relatedOccupation,
        hasHtbWorkRoute,
        hasSocCode,
        hasWorkingUniform,
        hasApprenticeshipLink,
        hasApprenticeshipRequirement,
        hasHtbCollegeRoute,
        hasHtbUniversityRoute,
        hasHtbVolunteeringRoute,
        requiresHtbRegistration,
        hasCollegeRequirement,
        hasCollegeLink,
        hasRequirementsPrefix,
        hasUniversityLink,
        hasUniversityRequirement,
        hasApprenticeshipStandard
    }
}
