variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'
    SolutionBaseName: 'DFC.App.JobProfile'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.15.0
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
    - msbuild
    - visualstudio

stages:
  - stage: Build
    displayName: Build, Test and Analyze
    jobs:
    - job: TestArmTemplates
      displayName: "Test & package ARM template(s)"
      steps:
        - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-arm-build.yml@dfc-devops
          parameters:
            ArmTemplateRoot: '${{ variables.ArmTemplateRoot }}'
            SolutionBaseName: '${{ variables.SolutionBaseName }}'

        - task: PublishPipelineArtifact@0
          displayName: Publish Page Registration artifact
          inputs:
            targetPath: '$(Build.SourcesDirectory)/Resources/PageRegistration'
            artifactName: ${{ variables.SolutionBaseName }}.PageRegistrations

        - task: PublishPipelineArtifact@1
          displayName: Publish Apim Policy
          inputs:
            targetPath: "$(System.DefaultWorkingDirectory)/Resources/ApimPolicy"
            artifactName: ${{ variables.SolutionBaseName }}.ApimPolicies

    #Build and test application
    - job: BuildDotNetCore
      displayName: Build-DotNetCore


      steps:
      # Build DFC.App.JobProfile
      - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
        parameters:
          SolutionBaseName: $(SolutionBaseName)
          BuildPlatform: $(BuildPlatform)
          BuildConfiguration: $(BuildConfiguration)
          PublishWebApp: true
          TestSuffix: UnitTests

      # Build DFC.App.JobProfile.MessageFunctionApp
      - template:  AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-notests.yml@dfc-devops
        parameters:
          SolutionBaseName: $(SolutionBaseName).MessageFunctionApp
          BuildPlatform: $(BuildPlatform)
          BuildConfiguration: $(BuildConfiguration)
          PublishWebApp: true

      # Build UI functional Tests
    - job: Builduifunctionaltests
      displayName: Build UI functional tests
      steps:
      # Build all UI Functional Tests that ends with UI.FunctionalTests
        - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
          parameters:
            SolutionBaseName: $(SolutionBaseName).UI.FunctionalTests
            BuildPlatform: $(BuildPlatform)
            BuildConfiguration: $(BuildConfiguration)

    - job: PublishOpenApiDefinition
      displayName: Publish Open Api Definition
      steps:
        - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-build-openapi-definition.yml@dfc-devops
          parameters:
            OpenApiDefinitionDirectory: $(Build.SourcesDirectory)\Resources\OpenApiDocs
            SolutionBaseName: $(SolutionBaseName)