variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'     
    SolutionBaseName: 'DFC.App.JobProfile'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.6.1
    endpoint: 'GitHub (ESFA)'

jobs:

#Build and test resources
- template: AzureDevOpsTemplates/Build/dfc-arm-build.yml@dfc-devops
  parameters:
    ArmTemplateRoot: $(ArmTemplateRoot)

#Build and test application
- job: BuildDotNetCore
  displayName: Build-DotNetCore
  pool:
    name: Continuous Integration 02 - SSD - 160ACU
    demands:
    - msbuild
    - visualstudio

  steps:
  # Build DFC.App.JobProfile
  - template: AzureDevOpsTemplates/Build/dfc-dotnetcore-build.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
      DotNetCoreVersion: 2.2.402
      PublishWebApp: true
      TestSuffix: UnitTests

  # Build DFC.App.JobProfile.MessageFunctionApp
  - template: AzureDevOpsTemplates/Build/dfc-dotnetcore-build-notests.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName).MessageFunctionApp
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
      DotNetCoreVersion: 2.2.402

  # Test DFC.App.JobProfile.DraftProfileService (an artifact will be built but isn't consumed in the release) 
  - template: AzureDevOpsTemplates/Build/dfc-dotnetcore-build.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName).DraftProfileService
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
      DotNetCoreVersion: 2.2.402
      TestSuffix: UnitTests

  # Test DFC.App.JobProfile.ProfileService (an artifact will be built but isn't consumed in the release) 
  - template: AzureDevOpsTemplates/Build/dfc-dotnetcore-build.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName).ProfileService
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
      DotNetCoreVersion: 2.2.402
      TestSuffix: UnitTests      
